<img src="images/LOGO_2.jpeg" width="450" height='450'/>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('/root/Desktop/visa.csv')

In [3]:
df.head()   # gives by default the top five rows of the data

Unnamed: 0          CASE_STATUS  \
0           1  CERTIFIED-WITHDRAWN   
1           2  CERTIFIED-WITHDRAWN   
2           3  CERTIFIED-WITHDRAWN   
3           4  CERTIFIED-WITHDRAWN   
4           5            WITHDRAWN   

                                       EMPLOYER_NAME  \
0                             UNIVERSITY OF MICHIGAN   
1                             GOODMAN NETWORKS, INC.   
2                          PORTS AMERICA GROUP, INC.   
3  GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY O...   
4                          PEABODY INVESTMENTS CORP.   

                        SOC_NAME                     JOB_TITLE  \
0  BIOCHEMISTS AND BIOPHYSICISTS  POSTDOCTORAL RESEARCH FELLOW   
1               CHIEF EXECUTIVES       CHIEF OPERATING OFFICER   
2               CHIEF EXECUTIVES         CHIEF PROCESS OFFICER   
3               CHIEF EXECUTIVES   REGIONAL PRESIDEN, AMERICAS   
4               CHIEF EXECUTIVES  PRESIDENT MONGOLIA AND INDIA   

  FULL_TIME_POSITION  PREVAILING_WAGE    YEAR                 WORKSITE  \
0                  N          36067.0  2016.0      ANN ARBOR, MICHIGAN   
1                  Y         242674.0  2016.0             PLANO, TEXAS   
2                  Y         193066.0  2016.0  JERSEY CITY, NEW JERSEY   
3                  Y         220314.0  2016.0         DENVER, COLORADO   
4                  Y         157518.4  2016.0      ST. LOUIS, MISSOURI   

          lon        lat  
0  -83.743038  42.280826  
1  -96.698886  33.019843  
2  -74.077642  40.728158  
3 -104.990251  39.739236  
4  -90.199404  38.627003

In [4]:
df.tail()    #gives bottom five rows of the data

Unnamed: 0 CASE_STATUS EMPLOYER_NAME SOC_NAME JOB_TITLE  \
3002453     3002454         NaN           NaN      NaN       NaN   
3002454     3002455         NaN           NaN      NaN       NaN   
3002455     3002456         NaN           NaN      NaN       NaN   
3002456     3002457         NaN           NaN      NaN       NaN   
3002457     3002458         NaN           NaN      NaN       NaN   

        FULL_TIME_POSITION  PREVAILING_WAGE  YEAR               WORKSITE  \
3002453                NaN              NaN   NaN          NYC, NEW YORK   
3002454                NaN              NaN   NaN      SOUTH LAKE, TEXAS   
3002455                NaN              NaN   NaN    CLINTON, NEW JERSEY   
3002456                NaN              NaN   NaN  OWINGS MILL, MARYLAND   
3002457                NaN              NaN   NaN       ALTANTA, GEORGIA   

               lon        lat  
3002453 -74.005941  40.712784  
3002454 -97.134178  32.941236  
3002455 -74.909890  40.636768  
3002456 -76.780253  39.419550  
3002457 -84.387982  33.748995

In [5]:
df.shape   #define the size of the data i.e (no. of rows * no. of columns)

(3002458, 11)

In [6]:
df.describe()   # To analyze the numeric column in the data

Unnamed: 0  PREVAILING_WAGE          YEAR           lon           lat
count  3.002458e+06     3.002373e+06  3.002445e+06  2.895216e+06  2.895216e+06
mean   1.501230e+06     1.469984e+05  2.013855e+03 -9.213441e+01  3.816054e+01
std    8.667351e+05     5.287609e+06  1.680612e+00  1.965591e+01  4.672835e+00
min    1.000000e+00     0.000000e+00  2.011000e+03 -1.578583e+02  1.343719e+01
25%    7.506152e+05     5.437100e+04  2.012000e+03 -1.119261e+02  3.416536e+01
50%    1.501230e+06     6.502100e+04  2.014000e+03 -8.615862e+01  3.910312e+01
75%    2.251844e+06     8.143200e+04  2.015000e+03 -7.551381e+01  4.088374e+01
max    3.002458e+06     6.997607e+09  2.016000e+03  1.457298e+02  6.483778e+01

In [7]:
df.isnull().sum()   # checking if there is any empty or missing values in the data

Unnamed: 0                 0
CASE_STATUS               13
EMPLOYER_NAME             59
SOC_NAME               17734
JOB_TITLE                 43
FULL_TIME_POSITION        15
PREVAILING_WAGE           85
YEAR                      13
WORKSITE                   0
lon                   107242
lat                   107242
dtype: int64

In [8]:
df.dropna(inplace=True)   # dropping the rows that have missing values since we have enormous data so there is no need to fill the missing value

In [9]:
df.drop('WORKSITE',axis=1,inplace=True)  # dropping the unnecessary columns

**Label Encoding refers to converting the labels into numeric form so as to convert it into the machine-readable form**

In [10]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

for i in df.columns:
    if isinstance(df[i][0], str):
            df[i] = encoder.fit_transform(df[i])

In [11]:
df.shape

(2877765, 10)

In [12]:
df.isnull().sum()

Unnamed: 0            0
CASE_STATUS           0
EMPLOYER_NAME         0
SOC_NAME              0
JOB_TITLE             0
FULL_TIME_POSITION    0
PREVAILING_WAGE       0
YEAR                  0
lon                   0
lat                   0
dtype: int64

# Model Training

In [13]:
feature_data = df.drop(['CASE_STATUS'], axis=1)

In [14]:
target_data = df.CASE_STATUS

In [15]:
cat_cols = list(feature_data.select_dtypes('object').columns)

In [16]:
num_cols = list(feature_data.select_dtypes('float64').columns)

In [17]:
cat_cols

[]

In [18]:
num_cols

['PREVAILING_WAGE', 'YEAR', 'lon', 'lat']

# Linear regression

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [20]:
trainx, testx, trainy, testy = train_test_split(feature_data, target_data)

In [21]:
log = LogisticRegression()

In [22]:
log.fit(trainx,trainy)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
pred = log.predict(testx)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
log.score(testx, testy)*100

87.356173256496

In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
confusion_matrix(testy,pred)

array([[628149,      0,      9,      0,      0],
       [ 48587,      0,      1,      0,      0],
       [ 21091,      0,    328,      0,      0],
       [     4,      0,      0,      0,      0],
       [ 21234,      0,     39,      0,      0]])

# Decission Tree Classifier

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
dtc = DecisionTreeClassifier()

In [29]:
dtc.fit(trainx, trainy)

DecisionTreeClassifier()

In [30]:
pred = dtc.predict(testx)

In [31]:
confusion_matrix(testy,pred)

array([[566397,  25134,  18950,      5,  17672],
       [ 20989,  24179,   1004,      0,   2416],
       [ 14733,   1026,   4606,      0,   1054],
       [     1,      1,      1,      0,      1],
       [ 13214,   2179,    991,      0,   4889]])

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
accuracy_score(testy,pred)*100

83.4078355169701

# GOOD LUCK

**About the Author**

<p>Hi! It's <a href="https://www.intellicial.in/">Intellicial Team</a> the author of this notebook. I hope you found this Notebook easy to learn!</p>

<p>Copyright © . <a href="https://www.intellicial.in/">Intellicial Innovations</a> .</p>